language: ruby
ruby:
- 2.4.3
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- nvm install v11.12.0
- nvm use v11.12.0
# - yarn add stimulus
env:
- ENV['RAILS_ENV'] = 'test'